name: Unit-Tests
description: Run unit tests parallel

runs:
  using: "composite"
  steps:
    - name: build
      uses: ./.github/actions/build

    - name: Count tests
      id: count_tests
      run: |
        TEST_COUNT=$(find ./dist/node -name "*.unit-test.js" | wc -l)
        echo "test_count=${TEST_COUNT}" >> $GITHUB_OUTPUT
        echo "Total test count: ${TEST_COUNT}"

    - name: Run unit tests
      env:
        TOTAL_TESTS: ${{ count_tests.outputs.test_count }}
        CHUNK: ${{ matrix.chunk }}
        CHUNKS: 8
      run: |
        echo "Total tests: $TOTAL_TESTS"
        echo "Current chunk: $CHUNK"
        echo "Total chunks: $CHUNKS"

        if [ -z "$TOTAL_TESTS" ] || [ "$TOTAL_TESTS" -eq 0 ]; then
          echo "Error: TOTAL_TESTS is not set or is zero. Exiting."
          exit 1
        fi

        start_index=$(( (TOTAL_TESTS * (CHUNK - 1) / CHUNKS) ))
        end_index=$(( (TOTAL_TESTS * CHUNK / CHUNKS) ))

        echo "Running tests from index $start_index to $end_index"

        shopt -s globstar
        test_files=(./dist/node/**/*.unit-test.js)

        set -o pipefail

        for ((i=start_index; i<end_index && i<${#test_files[@]}; i++)); do
            echo "Running test: ${test_files[$i]}"
            node --enable-source-maps "${test_files[$i]}" | tee -a profiling.md
        done
      continue-on-error: false

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.chunk }}
        path: profiling.md

    - name: Add to job summary
      if: always()
      run: |
        echo "### Test Results for Unit Tests Chunk ${{ matrix.chunk }}" >> $GITHUB_STEP_SUMMARY
        cat profiling.md >> $GITHUB_STEP_SUMMARY

