name: Check for Typos
# This workflow runs codespell to check for common misspellings in the codebase.

on:
  pull_request:
  push:
    branches:
      - main
      - v3
  workflow_dispatch: {}

jobs:
  codespell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run codespell
        uses: codespell-project/actions-codespell@master
        with:
          skip: "*.json,./node_modules,./dist,./.husky,./.git,./src/mina/**/*,./src/bindings/**/*"
          exclude_file: "./src/lib/provable/test/blake2b.unit-test.ts,./src/mina/README-dev.md"
          check_hidden: false
          ignore_words_list: "tHi,modul,optin,deriver,PRing,toWords,iSelf"