name: Check for Typos
# This workflow runs codespell to check for common misspellings in the codebase.
on:
  pull_request:
    types: [assigned, opened, synchronize, reopened, labeled, unlabeled]
  workflow_dispatch: {}

jobs:
  codespell:
    runs-on: ubuntu-latest
    # Skip the job if the PR has the specified tag/label
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no typo check') }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get changed files
        id: changed-files
        run: |
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "files=$(git diff --name-only --diff-filter=ACMRT ${{ github.event.pull_request.base.sha }} ${{ github.sha }} | tr '\n' ' ')" >> $GITHUB_OUTPUT
          else
            echo "files=." >> $GITHUB_OUTPUT
          fi
      
      - name: Run codespell on changed files
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          path: ${{ steps.changed-files.outputs.files }}
          skip: "*.json,./node_modules,./dist,./.husky,./.git,./src/mina/**/*,./src/bindings/**/*"
          check_hidden: false
          ignore_words_list: "tHi,modul,optin,deriver,PRing,toWords,iSelf"
