name: Lint, Format and Typo Check
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch: {}

jobs:
  lint-and-format:
    if: github.event.pull_request.labels.*.name != 'skip-lint'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Get Changed Files (Compare with Main)
        id: get_changed_files
        run: |
          git fetch origin main --depth=1
          # TODO ideally lint the non-generated files in src/bindings/
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.ref }} | grep -E '\.(ts|js)$' | grep -v 'src/bindings/*' || true)

          if [ -n "$CHANGED_FILES" ]; then
            echo "Files changed:"
            echo "$CHANGED_FILES"
            echo "$CHANGED_FILES" > changed_files.txt
            echo "files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No relevant files changed."
            echo "files_changed=false" >> $GITHUB_OUTPUT
          fi

      - name: Run Prettier Check
        if: steps.get_changed_files.outputs.files_changed == 'true'
        run: xargs npm run format:check < changed_files.txt

      - name: Run Oxlint
        if: steps.get_changed_files.outputs.files_changed == 'true'
        run: xargs npm run lint:strict < changed_files.txt

  check-for-typos:
    runs-on: ubuntu-latest
    # Skip the job if the PR has the specified tag/label
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'no typo check') }}
    steps:
      - uses: actions/checkout@v4
      - name: Get Changed Files (Compare with Main)
        id: get_changed_files
        run: |
          git fetch origin main --depth=1
          # TODO ideally lint the non-generated files in src/bindings/
          CHANGED_FILES=$(git diff --name-only ${{ github.event.pull_request.base.ref }} | grep -E '\.(ts|js)$' | grep -v 'src/bindings/*' || true)

          if [ -n "$CHANGED_FILES" ]; then
            echo "Files changed:"
            echo "$CHANGED_FILES"
            echo "$CHANGED_FILES" > changed_files.txt
            echo "files_changed=true" >> $GITHUB_OUTPUT
          else
            echo "No relevant files changed."
            echo "files_changed=false" >> $GITHUB_OUTPUT
          fi
    
      - name: Run codespell on changed files
        if: steps.get_changed_files.outputs.files_changed == 'true'
        uses: codespell-project/actions-codespell@master
        with:
          check_filenames: true
          path: ${{ steps.get_changed_files.outputs.files }}
          skip: "*.json,./node_modules,./dist,./.husky,./.git,./src/mina/**/*,./src/bindings/**/*"
          check_hidden: false
          ignore_words_list: "tHi,modul,optin,deriver,PRing,toWords,iSelf"

