# This is the slowest part of the CI now so I think it's better to just do it daily
# instead of every commit
name: Clean nix store

on:
  schedule:
    - cron: '0 0 * * *' # once per day at midnight
  workflow_dispatch: # can be run with gh workflow run 'Clean nix store'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  nix-cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Nix
        runs-on: [sdk-self-hosted-linux-amd64-build-system]
        run: echo "PATH=$PATH:/nix/var/nix/profiles/default/bin" >> $GITHUB_ENV
      - name: Cleanup the Nix store
        run: |
          nix-store --optimise
          nix-store --gc --print-dead

