name: Build and upload bindings
on:
  workflow_dispatch:
  workflow_call:

jobs:
  Upload-bindings:
    name: upload bindings artifact
    runs-on: [sdk-self-hosted-linux-amd64-build-system]
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Build
        uses: ./.github/actions/build
      - name: generate tar
        run: |
          set -Eeu
          ./pin.sh
          nix build o1js#bindings-tar --out-link bindings.tar.gz
      - name: Upload bindings
        uses: actions/upload-artifact@v4
        with:
          name: bindings.tar.gz
          path: bindings.tar.gz
